---
- name: Customize Parent Playbooks
  hosts: localhost

  tasks:
  - name: Set guid
    shell: uname -n | cut -c 9-13
    register : guid

  - name: Delete DEPRECATION WARNING
    lineinfile:
      path: /etc/ansible/ansible.cfg
      regexp: '^#deprecation_warnings = True'
      line: 'deprecation_warnings = False'
    become: true

- name: Transfer and execute a script.
  hosts: all
  vars:
    os-user: cloud-user
    
  tasks:
  - name: Backup rhsm.conf
    copy:
      src: /etc/rhsm/rhsm.conf
      dest: /etc/rhsm/rhsm.conf.sat-backup
      remote_src: true

  - name: Restore rhsm.conf
    copy:
      src: /etc/rhsm/rhsm.conf.kat-backup 
      dest: /etc/rhsm/rhsm.conf
      fource: true
      remote_src: true

  - name: Transfer the re-register script
    copy:
      src: "/home/{{ os-user }}/rhdp-pre4rhel/re-register.sh"
      dest: "/home/{{ os-user }}"
      mode: 0777

  - name: Execute the script
    command: "sh /home/{{ os-user }}/re-register.sh"

