---
- name: Customize Parent Playbooks
  hosts: localhost

  tasks:
  - name: Set guid
    shell: uname -n | cut -c 9-13
    register : guid

  - name: Delete DEPRECATION WARNING
    lineinfile:
      path: /etc/ansible/ansible.cfg
      regexp: '^#deprecation_warnings = True'
      line: 'deprecation_warnings = False'
    become: true

- name: Transfer and execute a script.
  hosts: all
  vars:
    os_user: cloud-user
    
  tasks:
  - name: Backup rhsm.conf
    copy:
      src: /etc/rhsm/rhsm.conf
      dest: /etc/rhsm/rhsm.conf.sat-backup
      remote_src: true

  - name: Restore rhsm.conf
    copy:
      src: /etc/rhsm/rhsm.conf.kat-backup 
      dest: /etc/rhsm/rhsm.conf
      fource: true
      remote_src: true

  - name: Transfer the re-register script
    copy:
      src: "/home/{{ os_user }}/rhdp-pre4rhel/re-register.sh"
      dest: "/home/{{ os_user }}"
      mode: 0777

  - name: Execute the re-register script
    command: "sh /home/{{ os_user }}/re-register.sh"

  - name: Turn On repository list creation
    lineinfile:
      path: /etc/rhsm/rhsm.conf
      regexp: 'manage_repos = 0'
      line: 'manage_repos = 1'
    become: true

  - name: Install SCAP
    dnf:
      name: "{{ item }}"
      state: latest
    loop:
      - scap-security-guide
      - openscap-scanner
      - openscap
      - yara

  - name: Transfer the insights script
    copy:
      src: "/home/{{ os_user }}/rhdp-pre4rhel/check-insights.sh"
      dest: "/home/{{ os_user }}"
      mode: 0777

  - name: Execute the insights script
    command: "sh /home/{{ os_user }}/check-insights.sh"
  
  - name: Turn On test scan
    lineinfile:
      path: /etc/insights-client/malware-detection-config.yml 
      regexp: 'test_scan false'
      line: 'test_scan true'
    become: true

  - name: Execute the insights script again
    command: "sh /home/{{ os_user }}/check-insights.sh"
  



  

  
  
