---
- name: Customize Parent Playbooks
  hosts: localhost

  tasks:
  - name: Set guid
    shell: uname -n | cut -c 9-13
    register : guid

  - name: Delete DEPRECATION WARNING
    lineinfile:
      path: /etc/ansible/ansible.cfg
      regexp: '^;deprecation_warnings=True'
#      regexp: '^#deprecation_warnings = True'
      line: 'deprecation_warnings = False'

- name: Transfer and execute a script.
  hosts: all
  vars:
    s_os_user: student
    t_os_user: ec2-user
    
  tasks:
  - name: Backup rhsm.conf
    copy:
      src: /etc/rhsm/rhsm.conf
      dest: /etc/rhsm/rhsm.conf.sat-backup
      remote_src: true

  - name: Restore rhsm.conf
    copy:
      src: /etc/rhsm/rhsm.conf.kat-backup 
      dest: /etc/rhsm/rhsm.conf
      force: true
      remote_src: true

  - name: Transfer the re-register script
    copy:
      src: "/home/{{ s_os_user }}/rhdp-pre4rhel/re-register.sh"
      dest: "/home/{{ t_os_user }}"
      mode: 0777

  - name: Execute the re-register script
    command: "sh /home/{{ t_os_user }}/re-register.sh"

  - name: Turn On repository list creation
    lineinfile:
      path: /etc/rhsm/rhsm.conf
      regexp: 'manage_repos = 0'
      line: 'manage_repos = 1'

  - name: Install SCAP
    dnf:
      name: "{{ item }}"
      state: latest
    loop:
      - scap-security-guide
      - openscap-scanner
      - openscap
      - yara

  - name: Output msg
    debug:
      msg: "Set SCAP policy on https://console.redhat.com/insights"

