---
- name: Customize Parent Playbooks
  hosts: localhost

  tasks:
  - name: Set guid
    shell: uname -n | cut -c 9-13
    register : guid

- name: Transfer and execute a script.
  hosts: all
  vars:
    s_os_user: student
    t_os_user: ec2-user
    
  tasks:
  - name: Transfer the insights script
    copy:
      src: "/home/{{ s_os_user }}/rhdp-pre4rhel/check-insights.sh"
      dest: "/home/{{ t_os_user }}"
      mode: 0777

  - name: Execute the insights script
    command: "sh /home/{{ t_os_user }}/check-insights.sh"
  
  - name: Turn On test scan
    lineinfile:
      path: /etc/insights-client/malware-detection-config.yml
      regexp: 'test_scan: true'
      line: 'test_scan: false'

  - name: Turn On process scan
    lineinfile:
      path: /etc/insights-client/malware-detection-config.yml
      regexp: 'scan_processes: false'
      line: 'scan_processes: true'

  - name: Get file1
    get_url:
      url: https://secure.eicar.org/eicar.com
      dest: "/home/{{ t_os_user }}/eicar.com"

  - name: Get file2
    get_url:
      url: https://secure.eicar.org/eicar.com.txt
      dest: "/home/{{ t_os_user }}/eicar.com.txt"

  - name: Get file3
    get_url:
      url: https://secure.eicar.org/eicar_com.zip
      dest: "/home/{{ t_os_user }}/eicar_com.zip"

  - name: Get file4
    get_url:
      url: https://secure.eicar.org/eicarcom2.zip
      dest: "/home/{{ t_os_user }}/eicarcom2.zip"

  - name: Execute the insights script again
    command: "sh /home/{{ t_os_user }}/check-insights.sh"
  